//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APlanner.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class APlannerEntities : DbContext
    {
        public APlannerEntities()
            : base("name=APlannerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Enroll> Enrolls { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<Mess> Messes { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Professor> Professors { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SPlan> SPlans { get; set; }
        public virtual DbSet<STime> STimes { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
    
        [DbFunction("APlannerEntities", "Course_View")]
        public virtual IQueryable<Course_View_Result> Course_View(Nullable<int> c)
        {
            var cParameter = c.HasValue ?
                new ObjectParameter("c", c) :
                new ObjectParameter("c", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Course_View_Result>("[APlannerEntities].[Course_View](@c)", cParameter);
        }
    
        [DbFunction("APlannerEntities", "Person_View")]
        public virtual IQueryable<Person_View_Result> Person_View(Nullable<int> c)
        {
            var cParameter = c.HasValue ?
                new ObjectParameter("c", c) :
                new ObjectParameter("c", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Person_View_Result>("[APlannerEntities].[Person_View](@c)", cParameter);
        }
    
        [DbFunction("APlannerEntities", "Schedule_View")]
        public virtual IQueryable<Schedule_View_Result> Schedule_View(Nullable<int> c)
        {
            var cParameter = c.HasValue ?
                new ObjectParameter("c", c) :
                new ObjectParameter("c", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Schedule_View_Result>("[APlannerEntities].[Schedule_View](@c)", cParameter);
        }
    }
}
