//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APlanner.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulePublicView
    {
        public string SUserID { get; set; }
        public string StudName { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> probability { get; set; }
        public Nullable<int> Credits { get; set; }
    }
}
