//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APlanner.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentView
    {
        public string SUserID { get; set; }
        public string StudName { get; set; }
        public string Major { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
