//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APlanner.APlannerDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class STime
    {
        public int SectID { get; set; }
        public string Classroom { get; set; }
        public int Period { get; set; }
        public int TermID { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Term Term { get; set; }
    }
}
